server:
  servlet:
    context-path: /loteria/app

spring:
  datasource:
    driver-class-name: ${LOTERIA_DB_DRIVER:org.h2.Driver}
    url: ${LOTERIA_DB_URL:jdbc:h2:mem:loteria-test}
    username: ${LOTERIA_DB_USERNAME:sa}
    password: ${LOTERIA_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      

      
      